export const ARTICLE_DETAIL = {
  user: {
    userSeq: 6,
    userId: "test3",
    email: "aaa2@c.com",
    introduction: null,
    userName: "민지",
    password: "$2a$10$KtrlPEyZYQUeOaIxymeiaOBno/NaRpVan/q2lhXQtrf5p3raAbuH2",
    nickname: "밍디",
    userTier: "BRONZE",
    challengeCount: 0,
    phoneNumber: "010-0110-0000",
    profileImageUrl: null,
  },
  status: 1,
  imageUrl: "url",
  expenditureCategory: 1,
  amount: 13333,
  articleText: "불금 글",
  articleType: 2,
  consumptionDate: "2023-05-19",
  writtenDate: "2023-05-21T18:07:48.104892",
  isAllowed: "false",
  commentCnt: 0,
  likeCnt: 0,
  agree: 0,
  disagree: 0,
  agreeRate: 0,
  disagreeRate: 0,
  mine: true,
  liked: false,
  voted: false,
};
